server:
  port: 8081

spring:
  application:
    name: dnadetector

  datasource:
    url: jdbc:mysql://localhost:3306/dna_detector?createDatabaseIfNotExist=true
    username: user
    password: user
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  jackson:
    default-property-inclusion: non_null
